version: "3"
services:
    db:
        build: ./ToDo.Server/Database/
        environment:
            SA_PASSWORD: "Password1234!"
            MSSQL_SA_PASSWORD: "Password1234!"
            SQLCMDPASSWORD: "Password1234!"
            ACCEPT_EULA: "Y"
    webapi:
        build: 
            context: .
            dockerfile: ./ToDo.Server/Dockerfile
        environment:
            ConnectionStrings__ToDo: "Server=db;Database=master;Encrypt=false;User=sa;Password=Password1234!;"
        ports:
            - "8080:8080"
        depends_on:
            - db
