version: "3"
services:
    db:
        build: ./ToDo.Server/Database/
        environment:
            SA_PASSWORD: "Password1234!"
            MSSQL_SA_PASSWORD: "Password1234!"
            SQLCMDPASSWORD: "Password1234!"
            ACCEPT_EULA: "Y"
    webapi:
        build: 
            context: .
            dockerfile: ./ToDo.Server/Dockerfile
        environment:
            ASPNETCORE_URLS: http://+:7043
            ConnectionStrings__ToDo: "Server=db;Database=master;Encrypt=false;User=sa;Password=Password1234!;"
            #CorsOptions__PolicyName: "TodoApiPolicy"
            #CorsOptions__AllowedOrigin: "http://localhost:3000"
        ports:
            - "5000:7043"
        depends_on:
            - db
#    webapp:
#        build:
#            context: ./src/todo-list-spa
#            args:
#                - api_url=http://localhost:5000
#        ports:
#            - "3000:80"
